### ISSUE TITLE
Incompatible version of 'image' library

### ISSUE THREAD

**Issue by Tails** [sami-badawi/shapelogic-rust#6]
Assuming the code would normally compile, it currently doesn't work because the image crate has changed its API. What is the concrete version of the 'image' crate that works for you when compiling? Should it be working with 0.23.12? And what Rust version? :)

```bash
error[E0599]: no method named `get_pixel` found for enum `DynamicImage` in the current scope
   --> src/image_operations.rs:42:26
    |
42  |             let px = img.get_pixel(x, y)
    |                          ^^^^^^^^^ method not found in `DynamicImage`

```
